# For more information: https://laravel.com/docs/sail
version: "3"
services:

  # Nginx
  web:
    image: nginx:latest
    ports:
      - "443:443"
    depends_on:
      - laravel.app
    volumes:
      - "$PWD/default.conf:/etc/nginx/conf.d/default.conf:ro" 
#      - "$PWD/public:/usr/share/nginx/html"

######################################################################
      # SSL証明(Nginxからroot権限で参照される)
      - "$SSL_CERTIFICATE_PATH:/etc/live/fullchain.pem:ro"
      - "$SSL_CERTIFICATE_KEY_PATH:/etc/live/privkey.pem:ro"
      # Logファイル
      - "$PWD/storage/logs/nginx:/var/log/nginx"

    networks:
      - sail

  laravel.app:  # ←名称を変更してはいけない（$APP_SERVICE、default.confと連動しているので、同じにすること。）
    build:
      context: ./docker/8.0
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: sail-8.0/app
    ports:
      - "${APP_PORT:-80}:80"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
    volumes:
      - "$PWD:/var/www/html"
    networks:
      - sail
    depends_on:
      - mysql
      - redis
      - selenium

  mysql:
    image: "mysql:8.0"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "$PWD/storage/volumes/mysql:/var/lib/mysql"
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]

  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "$PWD/storage/volumes/redis:/data"
    networks:
      - sail
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  meilisearch:
    image: "getmeili/meilisearch:latest"
    ports:
      - "${FORWARD_MEILISEARCH_PORT:-7700}:7700"
    volumes:
      - "$PWD/storage/volumes/meilisearch:/data.ms"
    networks:
      - sail

  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "${FORWARD_MAILHOG_PORT:-1025}:1025"
      - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025"
    networks:
      - sail

  selenium:
    image: "selenium/standalone-chrome"
    volumes:
      - "/dev/shm:/dev/shm"
    networks:
      - sail

networks:
  sail:
    driver: bridge
